version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/MyBoard_v1/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: auto-deploy.sh
      timeout: 60
      runas: ec2-user #ec2-user의 권한으로 deploy.sh를 실행하게됨